import 'reflect-metadata';
import { container } from 'tsyringe';
import { db, RedisService, CategoryRepository, SharedExpenseRepository, UserReadRepository } from '@financer/backend-shared';
import { OllamaProvider } from './providers/OllamaProvider';
import { OllamaOCRProvider } from './providers/OllamaOCRProvider';
import { PgVectorRepository } from './repositories/PgVectorRepository';
import { LLMChatRepository } from './repositories/LLMChatRepository';
import { BudgetReadRepository } from './repositories/BudgetReadRepository';
import { IncomeReadRepository } from './repositories/IncomeReadRepository';
import { CategorizationService } from './services/CategorizationService';
import { ChatService } from './services/ChatService';
import { LLMService } from './services/LLMService';
import { OCRService } from './services/OCRService';
import { FinancialToolService } from './tools/FinancialToolService';

container.register('db', { useValue: db });
container.register('ICacheService', { useClass: RedisService });
container.register('ILLMProvider', { useClass: OllamaProvider });
container.register('IOCRProvider', { useClass: OllamaOCRProvider });
container.register('IVectorRepository', { useClass: PgVectorRepository });
container.register('ILLMChatRepository', { useClass: LLMChatRepository });
container.register('ICategoryRepository', { useClass: CategoryRepository });
container.register('IExpenseRepository', { useClass: SharedExpenseRepository });
container.register('IBudgetRepository', { useClass: BudgetReadRepository });
container.register('IIncomeRepository', { useClass: IncomeReadRepository });
container.register('IUserReadRepository', { useClass: UserReadRepository });
container.register('IToolService', { useClass: FinancialToolService });
container.register('ICategorizationService', { useClass: CategorizationService });
container.register('IChatService', { useClass: ChatService });
container.register('ILLMService', { useClass: LLMService });
container.register('IOCRService', { useClass: OCRService });
